### ISSUE TITLE
Compile application [2-4h]

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/android_packages_apps_Calculator#1]
- [x] Open project in Android Studio
- [ ] Compile project with Gradle (generate APK)
- [ ] Documents steps to compile project in Google Drive
- [ ] Deploy APK to Android device to verify that everything is working properly

**Comment by jogrimst** [comment]
Gema, I get this error when invoking `./gradlew clean build`:

> Explanation for issues of type "ExtraTranslation":
>    If a string appears in a specific language translation file, but there is
>    no corresponding string in the default locale, then this string is probably
>    unused. (It's technically possible that your application is only intended
>    to run in a specific locale, but it's still a good idea to provide a
>    fallback.).
> 
>    Note that these strings can lead to crashes if the string is looked up on
>    any locale not providing a translation, so it's important to clean them
>    up.
> 
> 58 errors, 0 warnings
> :app:lintVitalRelease FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:lintVitalRelease'.
> > Lint found fatal errors while assembling a release target.
>   
>   To proceed, either fix the issues identified by lint, or modify your build script as follows:
>   ...
>   android {
>       lintOptions {
>           checkReleaseBuilds false
>           // Or, if you prefer, you can continue to check for errors in release builds,
>           // but continue the build even when errors are found:
>           abortOnError false
>       }
>   }
>   ...
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

So it seems like compilation fails because of some missing i18n. We only need English ("en") and Swahili ("sw"), so we can probably disable this lint checking.
