### ISSUE TITLE
Remove comma/division operator from widget [1-2h]

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/android_packages_apps_Calculator#24]

**Comment by jogrimst** [comment]
Also delete the operators from the widget:

![screenshot_20161104-125229](https://cloud.githubusercontent.com/assets/1451036/20001554/c3955854-a28d-11e6-844e-dfbc294d4be3.png)

**Comment by jogrimst** [comment]
@gscdev There is a second calculator widget which acts as an overlay on the screen. Do you think we should adapt that one also, or is it unlikely that the children will manage to activate it on their own?

**Comment by gscdev** [comment]
I had not seen it @jogrimst 

Access is similar for both widgets, and it is activated only touching a button.
Yes, I think that I should adapt it. If the children see a button, they will touch it.

I can add this task
Adapt floating calculator
- remove comma/division operator
- remove green pad with aditional operators
