### ISSUE TITLE
Move equal sign to the right column [4-8h]

### ISSUE THREAD

**Issue by jogrimst** [literacyapp-org/android_packages_apps_Calculator#32]
- [ ] App
- [ ] Widget
- [ ] Overlay widget

When testing the latest release of [CyanogenMod 13 on Nexus 7](http://download.cyanogenmod.org/?device=flo), the calculator looks like this, with the '=' sign in the right column instead of in the left column:

![screenshot_20161108-135927](https://cloud.githubusercontent.com/assets/1451036/20096914/fed4d8a4-a5bc-11e6-8b8c-d31206f82931.png)

@gscdev Now that we have more room since we are not using the division operator, do you think we should move the equals operator from the left to the right in order to create a clearer between numbers and operators?

**Comment by gscdev** [comment]
Yes, I'll move it @jogrimst
